name: CI/CD for Tip Model

on:
  push:
    branches:
      - main   # prod
      - dev    # dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag based on branch
        id: vars
        run: |
          echo "REPO_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "TAG=prod" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build and push Serving image
        run: |
          IMAGE_NAME=ghcr.io/${REPO_LC}/tip_model_serving
          echo "Building $IMAGE_NAME:$TAG"
          docker build -t $IMAGE_NAME:$TAG -f week_three_data_warehouse/Dockerfile.serving .
          docker push $IMAGE_NAME:$TAG

      - name: Build and push Retrain image
        run: |
          IMAGE_NAME=ghcr.io/${REPO_LC}/tip_model_retrain
          echo "Building $IMAGE_NAME:$TAG"
          docker build -t $IMAGE_NAME:$TAG -f week_three_data_warehouse/Dockerfile.retrain .
          docker push $IMAGE_NAME:$TAG
